package main

import "fmt"

// --- Dart Template ---
// Wire-format compatible with every other BitPacker target:
// VarInt + ZigZag ints, fixed-point floats (x10000 as VarInt64),
// length-prefixed UTF-8 strings, single-byte bools.
const tmplDart = `// Generated by BitPacker
// ignore_for_file: non_constant_identifier_names

import 'dart:convert';
import 'dart:typed_data';

const String VERSION = "{{.Config.Version}}";

// dart:typed_data already exports an Endian class, so this uses a Bp prefix.
enum BpEndian { big, little }

class ZeroCopyByteBuff {
  Uint8List writeBuf;
  int cursor = 0;
  final double multiplier = 10000.0;

  ZeroCopyByteBuff.writer([int size = 65536]) : writeBuf = Uint8List(size);

  ZeroCopyByteBuff.fromBytes(Uint8List data) : writeBuf = data;

  void ensureCapacity(int needed) {
    if (cursor + needed > writeBuf.length) {
      final newSize = (writeBuf.length * 2) > (cursor + needed)
          ? (writeBuf.length * 2)
          : (cursor + needed);
      final newBuf = Uint8List(newSize);
      newBuf.setRange(0, writeBuf.length, writeBuf);
      writeBuf = newBuf;
    }
  }

  // ZigZag 32
  static int zigzagEncode32(int n) {
    return ((n << 1) ^ (n >> 31)) & 0xFFFFFFFF;
  }

  static int zigzagDecode32(int n) {
    return (n >>> 1) ^ (-(n & 1));
  }

  // VarInt32
  void putVarInt32(int value) {
    ensureCapacity(5);
    value &= 0xFFFFFFFF;
    while ((value & ~0x7F) != 0) {
      writeBuf[cursor++] = (value & 0x7F) | 0x80;
      value >>>= 7;
    }
    writeBuf[cursor++] = value & 0xFF;
  }

  int getVarInt32() {
    int result = 0;
    int shift = 0;
    while (true) {
      final b = writeBuf[cursor++];
      result |= (b & 0x7F) << shift;
      if ((b & 0x80) == 0) break;
      shift += 7;
    }
    return result & 0xFFFFFFFF;
  }

  void putInt32(int val) {
    putVarInt32(zigzagEncode32(val));
  }

  int getInt32() {
    return zigzagDecode32(getVarInt32());
  }

  // VarInt64 (ZigZag)
  void putVarInt64(int val) {
    ensureCapacity(10);
    // ZigZag 64: (n << 1) ^ (n >> 63)
    int zz = (val << 1) ^ (val >> 63);
    while ((zz & ~0x7F) != 0) {
      writeBuf[cursor++] = (zz & 0x7F) | 0x80;
      zz >>>= 7;
    }
    writeBuf[cursor++] = zz & 0xFF;
  }

  int getVarInt64() {
    int result = 0;
    int shift = 0;
    while (true) {
      final b = writeBuf[cursor++];
      result |= (b & 0x7F) << shift;
      if ((b & 0x80) == 0) break;
      shift += 7;
    }
    // ZigZag Decode 64
    return (result >>> 1) ^ (-(result & 1));
  }

  void putInt64(int val) {
    putVarInt64(val);
  }

  int getInt64() {
    return getVarInt64();
  }

  void putFloat(double val) {
    // Multiply by scalar and store as int64.
    // floor(x + 0.5) matches JS Math.round for exact-half values.
    putVarInt64((val * multiplier + 0.5).floor());
  }

  double getFloat() {
    return getVarInt64() / multiplier;
  }

  void putBoolean(bool val) {
    ensureCapacity(1);
    writeBuf[cursor++] = val ? 1 : 0;
  }

  bool getBoolean() {
    return writeBuf[cursor++] != 0;
  }

  void putString(String val) {
    final bytes = utf8.encode(val);
    putInt32(bytes.length);
    ensureCapacity(bytes.length);
    writeBuf.setRange(cursor, cursor + bytes.length, bytes);
    cursor += bytes.length;
  }

  String getString() {
    final len = getInt32();
    if (len == 0) return "";
    final s = utf8.decode(writeBuf.sublist(cursor, cursor + len));
    cursor += len;
    return s;
  }

  Uint8List finish() {
    return Uint8List.sublistView(writeBuf, 0, cursor);
  }
}

{{range .Classes}}
class {{.Name}} {
  {{range .Fields}}{{if .IsArray}}List<{{mapTypeDart .Type}}> {{.Name}} = [];
  {{else}}{{mapTypeDart .Type}} {{.Name}} = {{defaultValueDart .Type}};
  {{end}}{{end}}
  {{.Name}}();

  Uint8List encode() {
    final buf = ZeroCopyByteBuff.writer(65536);
    buf.putString(VERSION);
    encodeTo(buf);
    return buf.finish();
  }

  void encodeTo(ZeroCopyByteBuff buf) {
    {{range .Fields}}{{if .IsArray}}buf.putInt32({{.Name}}.length);
    for (final item in {{.Name}}) {
      {{encodeFieldDart "item" "" "" .Type}}
    }
    {{else}}{{encodeFieldDart "this" "" .Name .Type}}
    {{end}}{{end}}
  }

  static {{.Name}} decode(Uint8List data) {
    final buf = ZeroCopyByteBuff.fromBytes(data);
    final version = buf.getString();
    if (version != VERSION) {
      throw StateError("Version Mismatch: Expected $VERSION, got $version");
    }
    return decodeFrom(buf);
  }

  static {{.Name}} decodeFrom(ZeroCopyByteBuff buf) {
    final obj = {{.Name}}();
    // explicit field order
    {{range .Fields}}{{if .IsArray}}final count_{{.Name}} = buf.getInt32();
    obj.{{.Name}} = [];
    for (var i = 0; i < count_{{.Name}}; i++) {
      {{decodeFieldDartAdd "obj" .Name .Type}}
    }
    {{else}}{{decodeFieldDart "obj" .Name .Type}}
    {{end}}{{end}}
    return obj;
  }
}
{{end}}
`

// --- Dart Helpers ---

func mapTypeDart(t string) string {
	switch t {
	case "int", "long", "short", "byte":
		return "int"
	case "float", "double":
		return "double"
	case "bool":
		return "bool"
	case "string":
		return "String"
	default:
		return t // Class name
	}
}

func defaultValueDart(t string) string {
	switch t {
	case "int", "long", "short", "byte":
		return "0"
	case "float", "double":
		return "0.0"
	case "bool":
		return "false"
	case "string":
		return "\"\""
	default:
		return t + "()"
	}
}

func encodeFieldDart(access, arrayIdx, fieldName, fieldType string) string {
	prefix := access
	if fieldName != "" {
		prefix = access + "." + fieldName
	}
	if access == "item" {
		prefix = "item"
	}

	switch fieldType {
	case "int":
		return fmt.Sprintf("buf.putInt32(%s);", prefix)
	case "long":
		return fmt.Sprintf("buf.putInt64(%s);", prefix)
	case "float", "double":
		return fmt.Sprintf("buf.putFloat(%s);", prefix)
	case "bool":
		return fmt.Sprintf("buf.putBoolean(%s);", prefix)
	case "string":
		return fmt.Sprintf("buf.putString(%s);", prefix)
	default: // Class
		return fmt.Sprintf("%s.encodeTo(buf);", prefix)
	}
}

func decodeFieldDart(objVar, fieldName, fieldType string) string {
	target := objVar + "." + fieldName

	switch fieldType {
	case "int":
		return fmt.Sprintf("%s = buf.getInt32();", target)
	case "long":
		return fmt.Sprintf("%s = buf.getInt64();", target)
	case "float", "double":
		return fmt.Sprintf("%s = buf.getFloat();", target)
	case "bool":
		return fmt.Sprintf("%s = buf.getBoolean();", target)
	case "string":
		return fmt.Sprintf("%s = buf.getString();", target)
	default: // Class
		return fmt.Sprintf("%s = %s.decodeFrom(buf);", target, fieldType)
	}
}

func decodeFieldDartAdd(objVar, fieldName, fieldType string) string {
	target := objVar + "." + fieldName

	switch fieldType {
	case "int":
		return fmt.Sprintf("%s.add(buf.getInt32());", target)
	case "long":
		return fmt.Sprintf("%s.add(buf.getInt64());", target)
	case "float", "double":
		return fmt.Sprintf("%s.add(buf.getFloat());", target)
	case "bool":
		return fmt.Sprintf("%s.add(buf.getBoolean());", target)
	case "string":
		return fmt.Sprintf("%s.add(buf.getString());", target)
	default: // Class
		return fmt.Sprintf("%s.add(%s.decodeFrom(buf));", target, fieldType)
	}
}
